### ISSUE TITLE
Comentarios de su documentación

### ISSUE THREAD

**Issue by monzter50** [RedEyes-Room/SIGMAA2#1]
Hola @RedEyes-Room, es importante que el nombre quede definido a más tardar este issues,  no es necesario escribir preámbulos al momento de redactar si es aplicación web o móvil; se recomienda expresar directamente es una aplicación web o móvil.

Su objetivo general debe reflejar la esencia del planteamiento del problema y la idea expresada, respondiendo las preguntas: ¿Qué? ¿Cómo? ¿Para qué?

Su objetivo específico se desprenden del general y deben ser formulados de forma que estén orientados al logro del objetivo general.

**Comment by DovoMaster** [comment]
Hola profesor buenas tardes. Ya se cambiaron los puntos marcados, no se si tenga algún otro comentario

**Comment by monzter50** [comment]
El planteamiento es correcto, verifica solo tu redacción al momento describir tu objetivo general y especifico te comparto algunos verbos y ejemplos que se manejan al redactar un objetivo general y especificos.

Determinar, Verificar, Definir, Identificar, Diseñar, Conocer, Evaluar, Elaborar, Estudiar, Describir, Proponer, Plantear, Formular, Analizar, Corroborar.

Ejemplo de un objetivo general:
Analizar la actitud de los directivos nacionales de la industria manufacturera respecto de la innovación y creatividad en sus organizaciones.

Ejemplo de un especifico.

* Elaborar un marco teórico sobre la actitud de los directivos de empresas respecto de la
innovación y creatividad en las organizaciones productivas.
* Diseñar un instrumento de medición de aptitudes con sus respectivas pruebas de validez y confiabilidad para aplicarlo a la población seleccionada.
* Identificar la actitud de los gerentes de las 100 empresas más grandes del país respecto de la innovación y la creatividad en ellas.
* Analizar los resultados obtenidos según subsector y demás variables sociodemográficas
de las empresas estudiadas.
