### ISSUE TITLE
Invitación administración de proyecto

### ISSUE THREAD

**Issue by monzter50** [RedEyes-Room/SIGMAA2#11]
Invitarme a cualquier software de administración de proyecto(trello,asana,jira,excel,etc..) y mencionarme que metodología usaran para gestionar su proyecto.

### Fecha limite 28 de marzo del 2020 antes de las 11:59 pm

**Comment by DGizmo** [comment]
Buenas tardes profesor aquí le dejamos la invitación a Trello : **https://trello.com/invite/b/oBvtyQzP/db21f34e9b653c8f91628b7f1dfa0073/red-eyes-room**
Y la metodología que usaremos es Kanban ya que se nos hace sencillo y las vimos como parte de la materia de administración de proyectos, ya dentro ya tenemos algunas tareas creadas y una en progreso.
