### ISSUE TITLE
Infografía UX y UI

### ISSUE THREAD

**Issue by monzter50** [RedEyes-Room/SIGMAA2#7]
# Elaborar 4 infografía (Individual)
* Habilidades de UX
* Habilidades de UI
* ¿Que es UX y UX?
* Diferencias entre UI y UX

## Fecha limite 07-03-2020 a las 11:59 pm

**Comment by DGizmo** [comment]
profesor buenas tardes, es una infografía incluyendo cada punto o 4 infografías con cada uno de los puntos que especifico?

**Comment by monzter50** [comment]
Hola buenas tardes, elaborar una infografía por cada punto.
